# Generated by Django 3.0.6 on 2020-06-11 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20200611_0535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='name',
            new_name='username',
        ),
    ]
